version: '3'
services:
 redis1:
  image: redis
  restart: always
  ports:
   - "6379:6379"
  command: redis-server --port 6379
 redis2:
  image: redis
  restart: always
  ports:
   - "6380:6379"
  command: redis-server --port 6379
 redis3:
  image: redis
  restart: always
  ports:
   - "6381:6379"
  command: redis-server --port 6379
